%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Interface Graphique ("calculatrice")


function calculatrice
 
handles.fenetre = figure ('units','pixels',...
        'Position',[600 200 800 600],...
        'color',rand(1,3),...
        'tag','fenetre');
 
handles.resultat = uicontrol('style','Text',...
          'string','0',...
          'fontsize',20,...
          'units','pixels',...
          'Position',[650 300 100 50 ],...
          'tag','resultat');
 
handles.donnee1= uicontrol('style','edit',...
        'string','0',...
        'fontsize',20,...
        'Units','pixels',...
        'position',[50 300 100 50],...
        'tag','donnee1');
 
handles.donnee2= uicontrol('style','edit',...
        'string','0',...
        'fontsize',20,...
        'Units','pixels',...
        'position',[300 300 100 50],...
        'tag','donnee2');
 
handles.plus= uicontrol('style','Text',...
          'string','+',...
          'fontsize',20,...
          'units','pixels',...
          'Position',[175 300 100 35 ],...
          'tag','+');
 
handles.equal= uicontrol('style','Text',...
          'string','=',...
          'fontsize',20,...
          'units','pixels',...
          'Position',[500 300 100 35 ],...
          'tag','=');
 
handles.add= uicontrol('style','pushbutton',...
        'string','Add',...
        'fontsize',20,...
        'Units','pixels',...
        'position',[400 150 100 50],...
        'tag','add',...
        'callback',@addition);
 
guidata(handles.fenetre, handles);
 
function addition(objet,event)
 
handles = guidata(objet);
 
a=get(handles.donnee1,'string');
b=get(handles.donnee2,'string');
c= str2double(a) + str2double(b);
set(handles.resultat,'string',str2double(c));
guidata(objet, handles);